version: 0.0
environment_variables:
    plaintext:
        "INPUT_FILE": "saml.yaml"
        "S3_BUCKET": ""
containers:
    LambdaFunctions:
        phases:
            install:
                commands:
                    - echo install npm
                    - npm install
                    - echo Installing Mocha....
                    - npm install -g Mocha
            pre_build:
                commands:
                    - Installing source NPM dependencies....
                    - npm install unit.js
            build:
                commands:
                    - echo Build stated on 'date'
                    - echo compiling the node.js code
                    - mocha test.js
            post_build:
                commands:
                    - echo Build completed on 'date'
                    - echo Spinning up environment
                    - aws cloudformation package --template $INPUT_FILE --s3-bucket $S3_BUCKET --output-template post-saml.yaml
        artifacts:
            files:
                - post-saml.yaml
                - beta.json
                - test.js
